### ISSUE TITLE
Mirror pass CLI arguments

### ISSUE THREAD

**Issue by asymmetric** [stchris/passage#78]
I noticed that the CLI commands differ form pass.

Have you considered aligning them with pass, so that passage could be used as a drop-in replacement, at least in terms of muscle memory and usage?

**Comment by stchris** [comment]
Hello and thanks for your suggestion. I kind of wanted to do my own thing and I wasn't sure which features would be put in so I made up my own commands and argument names.

That being said I have less time to work on this and my plan was to stop with the 1.0 release. If you wanted to maintain a fork which would also change the names to match pass I would gladly mention you in the README.

**Comment by stchris** [comment]
I left a comment in the README stating that I no longer am able to maintain this project.
